/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDYDEhGp97RzfrCS5ovrilA",
        engine: "mysql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-9aa299fd",
            securityGroupIds: [
                "sg-089fe578"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-479f021f",
                    availabilityZone: "ap-southeast-2c"
                },
                {
                    subnetId: "subnet-51223e18",
                    availabilityZone: "ap-southeast-2a"
                },
                {
                    subnetId: "subnet-7f4aa919",
                    availabilityZone: "ap-southeast-2b"
                }
            ]
        }
    }
}).schema({
    "tblContacts": a.model({
        ContactType: a.string().required(),
        Phone: a.string(),
        Address: a.string(),
        Email: a.string(),
        LeadId: a.integer().required()
    }).identifier([
        "ContactType",
        "LeadId"
    ]),
    "tblLeads": a.model({
        LeadId: a.integer().required(),
        LeadName: a.string().required(),
        LeadLastName: a.string().required(),
        DOB: a.date()
    }).identifier([
        "LeadId"
    ])
});
